### ISSUE TITLE
missing PHP 5.6 support // method name "list"

### ISSUE THREAD

**Issue by nostadt** [every-ecommerce/akeneo-api#1]
Hello dev-team,

I would like to use your PHP API Wrapper for Akeneo ^1.7 with PHP 5.6. Our target software currently does not support PHP 7 which is why we cannot upgrade yet.

I have started with your API wrapper today and from what I can say the only reason is this method `\Every\Akeneo\Api\Endpoint\AbstractEndpoint::list` as `list` is a reserved keyword.

Is there a chance that you release a version which supports PHP 5.6?

Best regards,

AMartinNo1

**Comment by lexcast** [comment]
Hi @AMartinNo1 
You're right, I wanted to match the akeneo api nomenclature.
I'll rename it to `listItems`.

**Comment by nostadt** [comment]
Thanks for the quick response & release :)

**Comment by lexcast** [comment]
Great :+1:
